apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "my-app.fullname" . }}
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "my-app.fullname" . }}-waypoint
  labels:
    istio.io/waypoint-for: all
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE

