apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "my-app.fullname" . }}
spec:
  parentRefs:
    - name: {{ include "my-app.fullname" . }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /echo
      backendRefs:
        - name: {{ include "my-app.fullname" . }}
          port: 80
