{{- /*
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "my-app.fullname" . }}
spec:
  gateways:
    - istio-ingress/gateway
  hosts:
    - k3s.local
    - {{ include "my-app.fullname" . }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.virtualService.prefix }}
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ include "my-app.fullname" . }}.default.svc.cluster.local
            port:
              number: 80
*/}}
